.TH NAME 2 "YEAR" "SYSTEMCALL CALL"
.SH NAME
.PP
\fBname\fR - short description
.SH SYNOPSIS
.PP
\fB#include <sysCall.h>\fR

\fBint sysCall(dataType1 param2, dataType2 param2, etc.);\fR
.TP
.B PARAMETERS
\fBparameters\fR - description
.TP

\fBLD_PRELOAD=overWrittenSysCalls.so; export LD_PRELOAD\fR
.SH DESCRIPTION
.PP

description
.SH RETURN VALUE
.PP
On success, returns 0. On error, returns __ and set someErrNo (if you implemented it)
.SH ERRORS
.PP

erros (mention if you didn't implement it)
.SH EXAMPLES
.PP

examples
.SH SEE ALSO
.PP

- built in function
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP

