.TH NAME 3 "YEAR" "__ FUNCTION"
.SH NAME
.PP
\fBname\fR - short description
.SH SYNOPSIS
.PP
\fBint sysCall(dataType1 param2, dataType2 param2, etc.);\fR
.TP
.B PARAMETERS
\fBparameters\fR - description
.SH DESCRIPTION
.PP

description
.SH RETURN VALUE
.PP

return vals
.SH EXAMPLES
.PP

examples
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP

