.TH BRACKETS_AND_SPECIAL_CHARS 5 "2019" "BRACKETS AND SPECIAL CHARACTERS MEANING MANUAL"
.PP
- \fB< >\fR	:- Anything required, but generic. Should be in camelCase if <3 words or so, otherwise use spaces
.br
- \fB|\fR		:- Or operator. Need spaces on both sides
.br
- \fB[ ]\fR	:- Anything optional. Should be in camelCase if <3 words or so, otherwise use spaces
.br
- \fB{}\fR	:- Important arguments, but the set could be empty. Should be in camelCase if <3 words or so, otherwise use spaces. Intended for use in programs where no args does something (except pull up help menu)
.br
- \fB:-\fR	:- A semicolon for options in programs, but used to differentiate between ":" since a semicolon is a common syntax. Always lined up with other ":-", followed by a space, and next letter is capital
.br
- \fB( )\fR	:- Used to add some detail about something. Try to use infrequently due to its use as normal syntax in coding languages
