.TH B 1 "2017" "CD BACK MANUAL"
.SH NAME
.PP
\fBb\fR - cd's to previous directory
.SH SYNOPSIS
.PP
b
.SH DESCRIPTION
.PP
A function that is works with the other components of the cd stack code. This function moves back to the 2nd most recent directory the user cd'ed into in the current shell (i.e. not the current directory that was cd'ed into)

If any of these values are empty, the program will print so.

This program works for both bash and zsh.
.SH OPTIONS
.PP
none
.SH SEE ALSO
.PP
- sMan.1
.br
- fMan.1
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP
- src/cdStack/

