.TH CHECKFORFILEERRVALS 1 "2025" "CHECK FOR FILE ERROR VALUES MANUAL"
.SH NAME
.PP
\fBcheckForFileErrVals.sh\fR - checks all file contents in the repository directory for error comments or values
.SH SYNOPSIS
.PP
checkForFileErrVals.sh
.SH DESCRIPTION
.PP
This program checks for a variety of error comments, values, or other itmes throughout the repository directory
.SH OPTIONS
.PP
-h, --help  :- prints help menu
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP
- src/checkForFileErrVals.sh
