.TH COMMAND_NAME TYPE "YEAR" "COMMAND_NAME MANUAL"
.SH NAME
.PP
\fBcommand\fR - short description
.SH SYNOPSIS
.PP

synopsis
.SH DESCRIPTION
.PP

description
.SH OPTIONS
.PP

options
.SH MODES
.PP

modes
.SH EXAMPLES
.PP

examples
.SH NOTES
.PP

notes
.SH SEE ALSO
.PP

see also
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP
- files and/or dirs
