.TH CREATESYMLINKSFROMCSV 1 "2022" "CREATES SYMLINKS FROM CSV MANUAL"
.SH NAME
.PP
\fBcreateSymLinksFromCsv.sh\fR - creating symlinks based on values in filesAndFolders.csv
.SH SYNOPSIS
.PP
createSymLinksFromCsv.sh [args]
.SH DESCRIPTION
.PP
This program creates or updates symlinks for files with non-zero symlink values in the symLinkNum column in filesAndFolders.csv
.SH OPTIONS
.PP
-h, --help  :- prints help menu
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP
- src/symLinkCreateAndUpdate/createSymLinksFromCsv.sh
