.TH MAKESTATS 1 "2024" "MAKE STATS MANUAL"
.SH NAME
.PP
\fBmakeStats.sh\fR - generates stats and tables about the repository and its file contents
.SH SYNOPSIS
.PP
makeStats.sh [args]
.SH DESCRIPTION
.PP
This program create stats about this repository and writes them to repoStats.txt
.SH OPTIONS
.PP
-h, --help  :- prints help menu
.SH ASSOCIATED SOURCE CODE DIRECTORIES AND/OR FILES
.PP
- src/makeStats.sh
